version: '3.8'

services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: 62.84.113.113
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - client
    environment:
      DATABASE_URL: 'mongodb://admin:123@mongo:27017/mongo?authSource=admin&directConnection=true'
  client:
    build: ../Frontend
    ports:
      - '80:80'
      - '8000:8000'
